# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/DOCUMENTS/Zone Documents/ToF/Documents/GitHub/multimeli/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 342)
        Form.setWindowTitle("Multi Meli ;-)")
        self.pushButton_ReponseA = QtWidgets.QPushButton(Form)
        self.pushButton_ReponseA.setGeometry(QtCore.QRect(46, 221, 79, 51))
        self.pushButton_ReponseA.setObjectName("pushButton_ReponseA")
        self.pushButton_ReponseB = QtWidgets.QPushButton(Form)
        self.pushButton_ReponseB.setGeometry(QtCore.QRect(156, 221, 79, 51))
        self.pushButton_ReponseB.setObjectName("pushButton_ReponseB")
        self.pushButton_ReponseC = QtWidgets.QPushButton(Form)
        self.pushButton_ReponseC.setGeometry(QtCore.QRect(262, 221, 79, 51))
        self.pushButton_ReponseC.setObjectName("pushButton_ReponseC")
        self.label_X = QtWidgets.QLabel(Form)
        self.label_X.setGeometry(QtCore.QRect(164, 20, 59, 79))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.label_X.setFont(font)
        self.label_X.setText("X")
        self.label_X.setScaledContents(False)
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X.setObjectName("label_X")
        self.label_Nbr1 = QtWidgets.QLabel(Form)
        self.label_Nbr1.setGeometry(QtCore.QRect(44, 20, 91, 79))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.label_Nbr1.setFont(font)
        self.label_Nbr1.setText("10")
        self.label_Nbr1.setScaledContents(False)
        self.label_Nbr1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Nbr1.setObjectName("label_Nbr1")
        self.label_Nbr2 = QtWidgets.QLabel(Form)
        self.label_Nbr2.setGeometry(QtCore.QRect(250, 20, 89, 79))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.label_Nbr2.setFont(font)
        self.label_Nbr2.setText("10")
        self.label_Nbr2.setScaledContents(False)
        self.label_Nbr2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Nbr2.setObjectName("label_Nbr2")
        self.label_Reponse_A = QtWidgets.QLabel(Form)
        self.label_Reponse_A.setGeometry(QtCore.QRect(44, 152, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Reponse_A.setFont(font)
        self.label_Reponse_A.setText("00")
        self.label_Reponse_A.setTextFormat(QtCore.Qt.AutoText)
        self.label_Reponse_A.setScaledContents(False)
        self.label_Reponse_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reponse_A.setObjectName("label_Reponse_A")
        self.label_Reponse_B = QtWidgets.QLabel(Form)
        self.label_Reponse_B.setGeometry(QtCore.QRect(152, 154, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Reponse_B.setFont(font)
        self.label_Reponse_B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Reponse_B.setText("00")
        self.label_Reponse_B.setTextFormat(QtCore.Qt.AutoText)
        self.label_Reponse_B.setScaledContents(False)
        self.label_Reponse_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reponse_B.setObjectName("label_Reponse_B")
        self.label_Reponse_C = QtWidgets.QLabel(Form)
        self.label_Reponse_C.setGeometry(QtCore.QRect(258, 154, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Reponse_C.setFont(font)
        self.label_Reponse_C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Reponse_C.setText("00")
        self.label_Reponse_C.setTextFormat(QtCore.Qt.AutoText)
        self.label_Reponse_C.setScaledContents(False)
        self.label_Reponse_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reponse_C.setObjectName("label_Reponse_C")
        self.label_Message_Reponse = QtWidgets.QLabel(Form)
        self.label_Message_Reponse.setGeometry(QtCore.QRect(72, 118, 243, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_Message_Reponse.setFont(font)
        self.label_Message_Reponse.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#00aa00;\">Bonne Reponse</span></p></body></html>")
        self.label_Message_Reponse.setTextFormat(QtCore.Qt.RichText)
        self.label_Message_Reponse.setScaledContents(False)
        self.label_Message_Reponse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Message_Reponse.setObjectName("label_Message_Reponse")
        self.checkBox_1 = QtWidgets.QCheckBox(Form)
        self.checkBox_1.setEnabled(False)
        self.checkBox_1.setGeometry(QtCore.QRect(100, 280, 41, 19))
        self.checkBox_1.setCheckable(True)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 280, 41, 19))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(210, 280, 41, 19))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(270, 280, 41, 19))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(100, 300, 41, 19))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 300, 41, 19))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(210, 300, 41, 19))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(270, 300, 31, 19))
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(160, 320, 41, 19))
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(210, 320, 41, 19))
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.progressBar_Cool = QtWidgets.QProgressBar(Form)
        self.progressBar_Cool.setGeometry(QtCore.QRect(366, 20, 31, 281))
        self.progressBar_Cool.setStyleSheet("selection-background-color: rgb(0, 127, 0);")
        self.progressBar_Cool.setProperty("value", 0)
        self.progressBar_Cool.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_Cool.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_Cool.setObjectName("progressBar_Cool")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(360, 310, 51, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_ReponseA.setText(_translate("Form", "REPONSE"))
        self.pushButton_ReponseB.setText(_translate("Form", "REPONSE"))
        self.pushButton_ReponseC.setText(_translate("Form", "REPONSE"))
        self.checkBox_1.setText(_translate("Form", "1"))
        self.checkBox_2.setText(_translate("Form", "2"))
        self.checkBox_3.setText(_translate("Form", "3"))
        self.checkBox_4.setText(_translate("Form", "4"))
        self.checkBox_5.setText(_translate("Form", "5"))
        self.checkBox_6.setText(_translate("Form", "6"))
        self.checkBox_7.setText(_translate("Form", "7"))
        self.checkBox_8.setText(_translate("Form", "8"))
        self.checkBox_9.setText(_translate("Form", "9"))
        self.checkBox_10.setText(_translate("Form", "10"))
        self.label.setText(_translate("Form", "100 %"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

